lectures/week-7/_1_monday/dawn/LearnAuth/config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create]

  delete 'logout' => 'sessions#destroy'
  

end

lectures/week-7/_1_monday/dawn/LearnAuth/app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true
  validates :password, length: { within: 6..40 }
  has_secure_password

end

lectures/week-7/_1_monday/dawn/LearnAuth/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  private
  def current_user
    #if @current_user is not defined set it equal to the result using the session hash given that exists
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_signed_in?
    current_user.present?
  end

  helper_method :current_user, :user_signed_in?
  
end

lectures/week-7/_1_monday/dawn/LearnAuth/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_username(params[:username])

    if @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:error] = "Invalid username & password combination"
      render :new
    end
  end

  def destroy
    # logout the user
    session[:user_id] = nil
    redirect_to root_path 
  end

end

lectures/week-7/_1_monday/dawn/LearnAuth/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      #happy state
      redirect_to root_path
    else #error state
      flash[:error] = @user.errors.full_messages.to_sentence
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

lectures/week-7/_1_monday/dawn/LearnAuth/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

lectures/week-7/_1_monday/dawn/LearnAuth/app/helpers/application_helper.rb
module ApplicationHelper
end

lectures/week-7/_1_monday/dawn/LearnAuth/app/helpers/users_helper.rb
module UsersHelper
end

lectures/week-7/_1_monday/dawn/LearnAuth/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LearnAuth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- logout btn -->

<% if user_signed_in? %>
  <%= link_to "Logout", logout_path, method: :delete %>
<% else %>
  <%= link_to "Login", new_session_path %>
<% end %>

<%= yield %>

</body>
</html>

lectures/week-7/_1_monday/dawn/LearnAuth/app/views/users/new.html.erb
<h1>New User Signup</h1>

<% flash.each do |key, value| %>
   <%= content_tag :div, value, class: "flash #{key}" %>
<% end %>

<%= form_for @user, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>

    <%= f.label :username %><br>
    <%= f.text_field :username %><br>

    <%= f.label :password %><br>
    <%= f.password_field :password %><br>

    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %><br>

    <%= f.submit "Signup" %>

<% end %>

lectures/week-7/_1_monday/dawn/LearnAuth/app/views/welcome/index.html.erb
<h1>Rails Auth!</h1>

<% if user_signed_in? %>
  <h3>Congrats! You are successfully logged in <%= current_user.username %>!</h3>
<% else %>
  <%= link_to "Signup", new_user_path %>
<% end %>